### ISSUE TITLE
Error opening pdf on the fly

### ISSUE THREAD

**Issue by esradral** [Jako/PDFResource#11]
Revo 2.5.1
I've installed pdfresource, set the live_pdf TV on a blank template with no other content other than [[*content]], created a simple resource using the blank template, ticked the live_pdf TV and changed the content type to PDF.
When I browse to the page chrome (v53) alerts with unable to load pdf. IE 11 alerts with File does not begin with %PDF - local-EWH-59-880.
I've updated reader to latest DC version.

I've no idea where I'm going wrong - can you help please :-(

**Comment by Jako** [comment]
Have you assigned the create_pdf template variable too? Maybe you better don't change the content type to PDF.

**Comment by esradral** [comment]
Thanks for the reply :-)
Changed the content type back to HTML but still the error.
Added the create_pdf TV to the template, ticked both on the resource but couldn't save the resource - just hung on saving.
Reinstalled pdfresource but made no difference

**Comment by Jako** [comment]
Which PHP version are you using? Could you display the PHP errors?

Am 14. Oktober 2016 um 07:40:23, esradral (notifications@github.com) schrieb:

Thanks for the reply :-)
Changed the content type back to HTML but still the error.
Added the create_pdf TV to the template, ticked both on the resource but couldn't save the resource - just hung on saving.
Reinstalled pdfresource but made no difference

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Thomas Jakobi · pARTout · Grafik + Design
Baumgarten 2 · 48727 Billerbeck
Tel +49 2543 930900 · Fax +49 2543 930902
Mobil +49 172 1771663 · Skype jako.partout
www.partout.info

**Comment by esradral** [comment]
Modx 2.5.1-pl(traditional)
PHP ver 5.6.23
Modx error log is not showing anything. I've checked the error log on cpanel (shared hosting) - not showing any errors. I don't think I can get to PHP error logs without contacting my host - will try.

**Comment by esradral** [comment]
Found the error
[14-Oct-2016 10:32:57 UTC] PHP Fatal error:  Call to undefined method mPDF::mPDF() in /home/sohowcou/public_html/core/components/pdfresource/model/modpdf/modpdf.class.php on line 96

I'm guessing I need to install mPDF? I thought I'd read pdfresource would work out of the box? Can you point me in the right direction for installing mPDF please. Sorry if I'm being dense.

**Comment by Jako** [comment]
Thanks. I have debugged this on my installation and prepare a new version. PDFResource has mPDF inside.

**Comment by esradral** [comment]
Brilliant - thanks very much :-)

**Comment by Jako** [comment]
Fixed with 1.5.5

**Comment by Jako** [comment]
You have to download it from [_packages](https://github.com/Jako/PDFResource/tree/master/_packages). I can’t upload it on MODX Extras because of a timeout.

**Comment by esradral** [comment]
SORTED - works a treat - thank you very much :-)
